version: '3.3'
services:
    nifi:
        container_name: poc_nifi
        image: apache/nifi:1.11.4
        user: root
        ports:
            - 8080:8080 
            - 9998:9998
        volumes:
            - ./files/:/nifi/files/
        networks:
            - app-network
    api:
        image: mhart/alpine-node:16
        container_name: api
        user: root
        ports:
            - "3000:3000"
        networks:
            - app-network
        volumes:
            - .:/usr/app/
            - ./node_modules:/usr/app/node_modules
        working_dir: /usr/app/
        command: npm run api
networks:
    app-network:
        driver: bridge
