version: '3.3'
services:
    nifi:
        container_name: poc_nifi
        image: apache/nifi:1.11.4
        user: root
        network_mode: bridge
        ports:
            - 8080:8080 
            - 9998:9998
        volumes:
            - ./files/
    api:
        image: openresty/openresty:alpine
        container_name: api
        network_mode: host
        ports:
            - "3000:3000"
